CI fail check for coverage and upgrade go

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -39,7 +39,7 @@ jobs:
       - name: Set up Go
         uses: actions/setup-go@v3
         with:
-          go-version: '1.21.4'
+          go-version: '1.23'
 
       - name: Install golangci-lint
         run: |
@@ -59,7 +59,7 @@ jobs:
       - name: Set up Go
         uses: actions/setup-go@v3
         with:
-          go-version: '1.21.4'
+          go-version: '1.23'
       
       - name: Run Go Tests with Coverage
         run: |
@@ -70,6 +70,16 @@ jobs:
         run: |
           echo "Displaying coverage summary as a table:"
           go tool cover -func=coverage.out
+
+      - name: Check coverage threshold
+        run: |
+          # Check coverage using the `go test` command with the -cover flag
+          COVERAGE=$(go test -coverprofile=coverage.out ./... | tail -n 10 | grep -Eo 'coverage: [0-9]+(\.[0-9]+)?%' | awk '{print $2}' | sed 's/%//')
+          echo "Coverage is $COVERAGE%"
+          if [ $(echo "$COVERAGE < 70" | bc) -eq 1 ]; then
+            echo "Coverage is below 70%, failing the build!"
+            exit 1
+          fi
 
   build-and-push-image:
     runs-on: ubuntu-latest
